### ISSUE TITLE
XmlRpcClient not found

### ISSUE THREAD

**Issue by fdbatista** [fillzero/apache-xmlrpc#1]
Hi dude.

After adding the dependency to pom file and installing, it only downloads `xmlrpc-common`, but it does not install XmlRpcClient.

Any idea why?

**Comment by fillzero** [comment]
Hi @fdbatista ,

You can add `xmlrpc-client` dependency in pom.xml, as shown below :

```
<dependency>
    <groupId>org.apache.xmlrpc</groupId>
    <artifactId>xmlrpc-client</artifactId>
    <version>3.1.3-2</version>
</dependency>
```

When you run `mvn compile`, you can check the console log, something like:
```
Downloading from fillzero-maven-repo: https://raw.githubusercontent.com/fillzero/apache-xmlrpc/master/maven-repo/repository/org/apache/xmlrpc/xmlrpc-client/3.1.3-2/xmlrpc-client-3.1.3-2.pom

Downloading from fillzero-maven-repo: https://raw.githubusercontent.com/fillzero/apache-xmlrpc/master/maven-repo/repository/org/apache/xmlrpc/xmlrpc-client/3.1.3-2/xmlrpc-client-3.1.3-2.jar
```

**Comment by fdbatista** [comment]
Yes, I really don't know what happened. Dependencies were being downloaded, but the packages were not available.

I just closed/reopen the application in Intellij and suddenly it started to work.
Thanks!
